name: Update

on:
  push:
  schedule:
    - cron: 30 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        rm -f ./Relay/Relay
        while true;do wget -T 15 -c http://cdn.arloor.com/tool/dnat -O ./Relay/Relay && break;done
    - name: Step 3 - Release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update